#Name of workflow
name: My test workflow

#define the trigger event
on: [push]

# Jobs in the workflow 
jobs:
   say-hello:
      runs-on: ubuntu-latest
      steps:
         - run: echo "Hello, GitHub actions"
   static-analysis:
      needs: [say-hello]
      runs-on: ubuntu-latest
      steps:
         - name: Check out this repo
           uses: actions/checkout@v3

         - name: Install dependencies
           run: sudo apt install -y build-essential python3 cppcheck

         - run: pwd

         - name: Run cppCheck
           run: cppcheck --enable=all --error-exitcode=1 main.c

   build-and-test:        
      needs: [static-analysis]
      runs-on: ubuntu-latest
      steps:
         - name: run test
           run: python3 test.py
